version: "3.8"

services:
  board-service:
    container_name: piece-service
    image: ${DOCKER_USERNAME}/piece-service:latest
    ports:
      - "8087:8087"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true