spring:
  DataSource:
    url: jdbc:mysql://${EC2_HOST}:3306/piece_of_cake
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EC2_HOST}:8761/eureka/